development: &default
  adapter: postgresql
  database: cove-studio-5-17-18
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000
  gssencmode: disable

test:
  <<: *default
  database: annos_test
