development: &default
  adapter: postgresql
  database: cove-studio-5-17-18
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000
  # If you have issues running the datbase
  # locally, try uncommenting the line below.
  # gssencmode: disable

test:
  <<: *default
  database: annos_test
